services:
  ember-core:
    build: .
    restart: always
    environment:
      COHERE_API_KEY: /run/secrets/cohere_api_key
      OPENAI_API_KEY: /run/secrets/openai_api_key
      PINECONE_API_KEY: /run/secrets/pinecone_api_key
      TRANSACTION_SERVICE_URL: http://transaction-executor
      FIREWORKS_API_KEY: /run/secrets/fireworks_api_key
      OPENROUTER_API_KEY: /run/secrets/openrouter_api_key
      COINGECKO_API_KEY: /run/secrets/coingecko_api_key
      USE_COINGECKO_PRO_API: ${USE_COINGECKO_PRO_API}
      DISABLE_TRANSACTION_SIGNING_URL: ${DISABLE_TRANSACTION_SIGNING_URL}
    networks:
      - shared_network
    secrets:
      - cohere_api_key
      - openai_api_key
      - pinecone_api_key
      - fireworks_api_key
      - openrouter_api_key
      - coingecko_api_key
    logging:
      options:
        max-size: "1m"
        max-file: "1"

networks:
  shared_network:
    name: ember-main-${ENVIRONMENT}
    external: true

secrets:
  cohere_api_key:
    environment: "COHERE_API_KEY"
  openai_api_key:
    environment: "OPENAI_API_KEY"
  pinecone_api_key:
    environment: "PINECONE_API_KEY"
  fireworks_api_key:
    environment: "FIREWORKS_API_KEY"
  openrouter_api_key:
    environment: "OPENROUTER_API_KEY"
  coingecko_api_key:
    environment: "COINGECKO_API_KEY"
