version: '3.9'

services:
  ember-agents-staging:
    image: ember-agents-server
    build: .
    ports:
      - "8101:8101"
    working_dir: /app
    volumes:
      - ../:/app
    restart: always
    logging:
      options:
        max-size: "1m"
        max-file: "1"
    # command: bash -c "while true; do sleep 1000; done"
    # command: ./scripts/start.sh
    command: bash -c "sleep 2 && && echo `exiting with error...` && exit 1"
    networks:
      - shared_network

networks:
  shared_network:
    external: true
