name: Server Deployment (Production)

on: workflow_dispatch

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set up SSH environment
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" >> ~/.ssh/known_hosts

      - name: Setup SSH private key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: v2.21.0

      - name: Deploy containers in server
        env:
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          ENVIRONMENT: production
          DOCKER_HOST: ssh://${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}
          FIREWORKS_API_KEY: ${{ secrets.FIREWORKS_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
          USE_COINGECKO_PRO_API: ${{ vars.USE_COINGECKO_PRO_API }}
          DISABLE_TRANSACTION_SIGNING_URL: ${{ vars.DISABLE_TRANSACTION_SIGNING_URL }}
          BIRDEYE_API_KEY: ${{ secrets.BIRDEYE_API_KEY }}
        run: |
          docker compose -f compose.yaml -p brokeshire-core-$ENVIRONMENT up -d --build
