name: Server Deployment (Staging)

on:
  push:
    branches: [main]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set up .env file
        run: |
          echo "COHERE_API_KEY=${{ secrets.COHERE_API_KEY }}" >> .env
          echo "OAI_CONFIG_LIST=${{ secrets.OAI_CONFIG_LIST }}" >> .env
          echo "SSH_HOST=${{ vars.SSH_HOST }}" >> .env

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/ember-github
          chmod 600 ~/.ssh/ember-github
          ssh-keyscan -H ${{ vars.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Copy repository to server
        run: |
          rsync -Pavz -e "ssh -i ~/.ssh/ember-github" . ${{ secrets.SSH_USERNAME }}@${{ vars.SSH_HOST }}:/opt/staging/ember-core --exclude=".git"

      - name: Execute deployment script on remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/staging/ember-core
            ./scripts/staging.bash